### ISSUE TITLE
Android pushes is not coming to device

### ISSUE THREAD

**Issue by CrackerakiUA** [pushy-me/pushy-cordova#24] opened 2020-03-21 18:45 UTC
With latest version of pushy, I have ios release which works smoothly and android which don't receive pushes. Register device works, `Pushy.listen` function exists and called normally. What can we do about that, how can we debug that?

**Comment by pushy** [comment] 2020-03-21 20:16
Hi @CrackerakiUA,
If you could please provide the following information about the device experiencing this issue, that would be great:

1) Device manufacturer
2) Device model name
3) Android OS version

**Comment by dmaksiuta** [comment] 2020-03-23 14:27
@pushy-me 
1. Xiaomi
2. Redmi 4X
3. Android 7.1.2

**Comment by CrackerakiUA** [comment] 2020-03-23 14:27
1. blackview
2. BV9000 pro
3. 8.1.0

**Comment by Kondruk** [comment] 2020-03-23 14:35
@pushy-me Pushy working only at background. But if I want to turn off the app the Pushy isn't sending
1. Xiaomi
2. Mi 9t ( K20)
3. 10 QKQ1.190825.002

**Comment by pushy** [comment] 2020-03-24 21:48
Chinese-based devices such as Huawei and Xiaomi may not receive notifications after your app is swiped away from the recent apps menu, goes to background, or after a device reboot due to custom power saving features which affect Firebase Cloud Messaging as well.

Most notably, Chinese devices from the following manufacturers include custom power-saving restrictions which may hinder background notification delivery for your app:

Xiaomi
Huawei
OnePlus
Samsung
Oppo
Vivo
Asus
Sony
Honor

Read more about this issue:
https://dontkillmyapp.com/problem

The recommended solution is to instruct the user to whitelist your app from the respective manufacturer's power saving mechanism in the device settings. The instructions for doing this vary from one manufacturer to another.

Another solution that may work in some cases is to implement our [FCM Fallback Delivery](https://pushy.me/docs/resources/fcm-fallback-delivery) feature, which may improve delivery rates to some of these devices by attempting to deliver simultaneously through FCM.

We apologize for this inconvenience introduced by Chinese device manufacturers.

**Comment by CrackerakiUA** [comment] 2020-05-06 14:09
@pushy-me can you bring it back? this has nothing to do with devices, on the same device your demo app works correctly and our cordova app is not. Would be nice to have cordova demo app lib

**Comment by pushy** [comment] 2020-05-07 21:26
Hi @CrackerakiUA,
Sure thing. The issue has been reopened.

We've just published a Cordova demo app:
https://github.com/pushy-me/pushy-demo-cordova

Please give it a try and try to reproduce the issue there.

**Comment by pushy** [comment] 2020-05-18 17:41
@CrackerakiUA Please let us know if you were able to reproduce the issue in our Cordova demo app. Closing for now.

**Closed as completed by pushy** 2020-05-18 17:41 UTC
