### ISSUE TITLE
Pushy.register does not resolve on iOS

### ISSUE THREAD

**Issue by tawakol** [pushy-me/pushy-cordova#37] opened 2022-06-12 09:11 UTC
Hello, 

I've been getting reports lately that our iOS users have stopped receiving notifications and after some investigation it seems that the register function has stopped resolving a token on iOS, and so I'm not able to save that token in my backend. 

The same exact functionality resolves a token as expected on Android. 

I'm on the latest version of the pushy-cordova plugin and running iOS 15.5.

There's nothing in the way of error logs in XCode or anything, and it does show the plugin being called:

`To Native Cordova ->  PushyPlugin register PushyPlugin1072095995 ["options": []]`

Then it never actually resolves anything.

Please let me know if there's any other info I can share that would help.

**Comment by pushy** [comment] 2022-06-12 18:40
Hi @tawakol,
Thanks for filing an issue report. We'd be glad to assist.

If the `Pushy.register()` callback isn't invoked in your iOS app, please ensure your project isn't using any other push notification library, such as Firebase Cloud Messaging, Firebase Auth, APNs, OneSignal, React Native Push Notification, etc.

These libraries clash with the Pushy iOS SDK as they hook into (swizzle) the APNs methods which the Pushy iOS SDK relies on.

Also, please make sure your `AppDelegate` class does not override any of the following APNs methods:

1. `application:didRegisterForRemoteNotificationsWithDeviceToken`
2. `application:didFailToRegisterForRemoteNotificationsWithError`
3. `application:didReceiveRemoteNotification:fetchCompletionHandler`

If you'd like to use multiple push libraries at the same time, please see [this article](https://support.pushy.me/hc/en-us/articles/360053017131) to disable swizzling in the Pushy iOS SDK while invoking our internal methods manually in each AppDelegate APNs callback.

**iOS 13:** Due to a bug in iOS 13, the pushy.register() callback may never be called when your device is connected through Wi-Fi in rare scenarios. The only solution appears to be to temporarily connect to a different Wi-Fi network, or connecting through cellular instead. This bug was fixed by Apple in later versions of iOS.

Please let us know if this resolves the issue, or if you still need further assistance.

**Comment by tawakol** [comment] 2022-06-13 08:33
Hey there,

It seems I had the capacitor/FCM plugin installed and I didn't realize. Is it required by any chance for the FCM fallback? 

When I removed it everything is working as it should be.

Apologize for the oversight and thank you for your help!

**Comment by pushy** [comment] 2022-06-14 16:50
Hi @tawakol,
Glad to hear the issue is resolved.

While the FCM Android libraries (referenced inside `app/build.gradle`) are required for [FCM Fallback Delivery](https://pushy.me/docs/resources/fcm-fallback-delivery), the FCM plugin for Cordova should not be integrated directly as it will hook into the APNs delegate methods by default and break Pushy's iOS notification delivery capability.

If you'd like to integrate FCM Fallback Delivery, please follow instructions in the docs to import the FCM Android libraries in the `app/build.gradle` file.

**Closed as completed by pushy** 2022-06-14 16:50 UTC
